settings:
  title: 'Status Page 状态页面'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 15 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational/所有服务运行正常'
  notAllmonitorsOperational: 'Not All Systems Operational/部分服务出现故障'
  monitorLabelOperational: 'Operational/正常'
  monitorLabelNotOperational: 'Not Operational/故障'
  monitorLabelNoData: 'No data/无数据'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: ks-xzj678 # unique identifier
    name: ks.xzj678.eu.org
    description: '负责内容发布以及ngcz服务。由Cloudflare提供CDN加速和Tunnel服务。' # default=empty
    url: 'https://ks.xzj678.eu.org/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

#   - id: test-cf
#    name: www.cloudflare.com
#     description: 'Built for anything connected to the Internet.'
#     url: 'https://www.cloudflare.com'
#     method: GET
#     expectStatus: 200
#     linkable: true # allows the title to be a link, default=true

#   - id: blog-cloudflare-com
#     name: The Cloudflare Blog
#     url: 'https://blog.cloudflare.com/'
#     method: GET
#     expectStatus: 200
