settings:
  title: '状态页面'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational/当前所有服务运行正常'
  notAllmonitorsOperational: 'Not All Systems Operational/当前部分服务出现故障'
  monitorLabelOperational: 'Operational/正常'
  monitorLabelNotOperational: 'Not Operational/故障'
  monitorLabelNoData: 'No data/无数据'
  dayInHistogramNoData: 'No data/无数据'
  dayInHistogramOperational: 'All good/全部正常'
  dayInHistogramNotOperational: ' 次停机/incident(s)' # xx incident(s) recorded

monitors:
  - id: ks-xzj678 # unique identifier
    name: ks.xzj678.eu.org
    description: '负责部分内容发布以及ngcz直播地址获取服务。由Cloudflare提供CDN加速和Tunnel服务。' # default=empty
    url: 'https://ks.xzj678.eu.org/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: serv00-s3
    name: jerryxu.serv00.net&p01.jerryxu.serv00.net
    description: '在Serv00(s3)上的主机,目前暂无用途;同样在s3上，目前用于Vle*s代理服务。'
    url: 'https://jerryxu.serv00.net' 
    method: GET 
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true

#   - id: blog-cloudflare-com
#     name: The Cloudflare Blog
#     url: 'https://blog.cloudflare.com/'
#     method: GET
#     expectStatus: 200
